# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "ayumirage"

# Starship modules
[character]
success_symbol = "[[󰄛](success) ❯](symbol)"
error_symbol = "[[󰄛](error) ❯](symbol)"
vimcmd_symbol = "[󰄛 ❮](status)"

[git_branch]
style = "bold branch"

[directory]
truncation_length = 4
style = "bold directory"


[palettes.ayumirage]
error = "#f28779"
success = "#d5ff80"
directory = "#ffd173"
branch = "#f28779"
symbol = "#73d0ff"
status = "#dfbfff"
python = "#facc6e"
go = "#6dcbfa"
node = "#90e1c6"
rust = "#90e1c6"
